### ISSUE TITLE
Trailing alignment option

### ISSUE THREAD

**Issue by skywalkerlw** [diniska/swiftui-wrapping-stack#4]
Is there an option to allow trailing alignment?

**Comment by diniska** [comment]
Have you tried `.trailing`?

**Comment by skywalkerlw** [comment]
I'm using the way like 

```swift
WrappingHStack(id: \.self, alignment:.trailing, horizontalSpacing: 0, verticalSpacing: 12) {
                ForEach(item.operations, id: \.self) { operation in
                    Service.ActionButtonView(item: item,
                                             operation: operation,
                                             tasks: $tasks,
                                             onSuccess: onSuccess,
                                             onFailure: onFailure)
                }
            }.frame(minWidth: 0, maxWidth: .infinity).background(Color.red)
```

but comes a result of

![image](https://user-images.githubusercontent.com/2090084/126864704-8d5a6bb4-2a0f-4248-8ecc-ac49fc4db46a.png)

**Comment by diniska** [comment]
From what I see here, the buttons are aligned towards the right side of the screen which is trailing for this language.
How do you expect it to work?

**Comment by skywalkerlw** [comment]
hi, Thanks for quick reponse.

My keypoint the part of green box.  There should no this kind of area if you declare trailing alignment.

![image](https://user-images.githubusercontent.com/2090084/126881837-9c7d2dcc-1500-47af-9ada-7c18372ac2db.png)

**Comment by skywalkerlw** [comment]
One more issue is: If you have only 1 item and you set alignment = trailing. The result is still left aligned.

My expectation of `trailing alignment`:
- the children views is right aligned;
- no padding on the right side

![image](https://user-images.githubusercontent.com/2090084/126882081-6f6e51fb-a91f-4005-9f15-835f810f0284.png)

**Comment by diniska** [comment]
Thanks for the description @skywalkerlw . I have created pull requests to fix the mentioned issue: https://github.com/diniska/swiftui-wrapping-stack/pull/5.

I'd like you to try if this fixes the issue for you if that's ok. To do so you can use branch `alignment-fix` in the SwiftPM setting in the Xcode.

Please, let me know how it goes so that I can merge the pull request for everyone to use.

**Comment by diniska** [comment]
The new version is ready: https://github.com/diniska/swiftui-wrapping-stack/releases/tag/1.0.1. Thanks for contributing @skywalkerlw! Please, close the issue if this is fixed for you.
